import type { Metadata } from "next";
import "./globals.css";
import {CartProvider} from "@/contexts/cartContext";
import {AuthProvider} from "@/contexts/authContext";
import {NotificationsProvider} from "@/contexts/notificationContext";
import {Toaster} from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <CartProvider>
          <NotificationsProvider>
            <body className={`antialiased font-literata bg-white`}>
              <main>{children}</main>
              <Toaster />
            </body>
          </NotificationsProvider>
        </CartProvider>
      </AuthProvider>
    </html>
  );
}
